org: artemmagej
app: sls-shortlinker-app
service: shortlinker-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline
functions:
  api:
    handler: index.hello
    events:
      - httpApi:
          path: /
          method: get
