org: artemmagej
app: sls-shortlinker-app
service: shortlinker-http-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    NODE_ENV: ${sls:stage}
    URL_TABLE_NAME: ${self:service}-urlTable-${sls:stage}
    USER_TABLE_NAME: ${self:service}-userTable-${sls:stage}

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-auto-swagger
  - serverless-iam-roles-per-function
  - serverless-dynamodb-global-table-v2-plugin
  - serverless-dynamodb
  - serverless-offline

functions:
  test:
    handler: handler.test
    events:
      - httpApi:
          path: /
          method: get
  signUp:
    handler: handler.signUp
    events:
      - httpApi:
          path: /auth/sign-up
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:GetItem'
          - 'dynamodb:PutItem'
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_TABLE_NAME}'
  signIn:
    handler: handler.signIn
    events:
      - httpApi:
          path: /auth/sign-in
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:GetItem'
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_TABLE_NAME}'
  createShortUrl:
    handler: handler.createShortUrl
    events:
      - httpApi:
          path: /short-url
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:PutItem'
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.URL_TABLE_NAME}'
  redirectShortUrl:
    handler: handler.redirectShortUrl
    events:
      - httpApi:
          path: /{shortId}
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'dynamodb:GetItem'
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.URL_TABLE_NAME}'
  signUp: ${file(src/functions/auth/auth.yml):signUp}
  signIn: ${file(src/functions/auth/auth.yml):signIn}
  createShortUrl: ${file(src/functions/url/url.yml):createShortUrl}
  redirectShortUrl: ${file(src/functions/url/url.yml):redirectShortUrl}

custom:
  globalTablesV2:
    primaryRegion: us-east-1
    tables:
      - table: UserTable
        addRegions:
          - eu-west-1
      - table: UrlTable
        addRegions:
          - eu-west-1
  esbuild:
    bundle: true
    minify: false
    target: 'node18'
    platform: 'node'
  serverless-dynamodb:
    stages:
      - dev
    start:
      noStart: true
      port: 8000
      docker: true
      migrate: true
      seed: true
  autoswagger:
    title: 'AWS Short Linker'
    apiType: 'httpApi'
    typefiles: ['./src/types/api-types.d.ts']
    generateSwaggerOnDeploy: true
    apiKeyHeaders: ['authorization']
resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: UserIndex
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.URL_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: UserIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
