org: artemmagej
app: sls-shortlinker-app
service: shortlinker-http-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    NODE_ENV: ${sls:stage}
    URL_TABLE_NAME: ${self:service}-urlTable-${sls:stage}
    USER_TABLE_NAME: ${self:service}-userTable-${sls:stage}
  httpApi:
    authorizers:
      jwtAuthorizer:
        type: request
        functionName: jwtAuthorizer
        identitySource: [$request.header.Authorization]
plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-auto-swagger
  - serverless-iam-roles-per-function
  - serverless-dynamodb-global-table-v2-plugin
  - serverless-dynamodb
  - serverless-offline

functions:
  jwtAuthorizer:
    handler: handler.authenticate
  signUp: ${file(src/functions/auth/auth.yml):signUp}
  signIn: ${file(src/functions/auth/auth.yml):signIn}
  createShortUrl: ${file(src/functions/shortUrl/url.yml):createShortUrl}
  redirectShortUrl: ${file(src/functions/shortUrl/url.yml):redirectShortUrl}
  deactivateShortUrl: ${file(src/functions/shortUrl/url.yml):deactivateShortUrl}

custom:
  serverless-offline:
    ignoreJWTSignature: true
  globalTablesV2:
    primaryRegion: us-east-1
    tables:
      - table: UserTable
        addRegions:
          - eu-west-1
      - table: UrlTable
        addRegions:
          - eu-west-1
  esbuild:
    bundle: true
    minify: false
    target: 'node18'
    platform: 'node'
  serverless-dynamodb:
    stages:
      - dev
    start:
      noStart: true
      port: 8000
      docker: true
      migrate: true
      seed: true
  autoswagger:
    title: 'AWS Short Linker'
    apiType: 'httpApi'
    typefiles: ['./src/types/api-types.d.ts']
    generateSwaggerOnDeploy: true
    apiKeyHeaders: ['authorization']
resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.URL_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userEmail
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: UserIndex
            KeySchema:
              - AttributeName: userEmail
                KeyType: HASH
            Projection:
              ProjectionType: ALL
